version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my-postgres-compose
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: myuser 
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
