version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my-postgres-compose
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: demo
    ports:
      - "5432:5432"


