name: Add Label on Issue Close

on:
  issues:
    types: [closed]

jobs:
  add-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'Review' label
        if: github.event.issue.state == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Ready for Review']
            });